#############################################################################
# Makefile for building: bss-hmi
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  bss-hmi.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile bss-hmi.pro -config release
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_MQTT_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtMqtt -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = bss-hmi1.0.0
DISTDIR = /home/tuan/Desktop/bss-hmi/bss-hmi-qt/.tmp/bss-hmi1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Mqtt -lQt5Network -lQt5SerialPort -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Data/Datasource/linkdirector.cpp \
		Data/Model/basemodel.cpp \
		Data/Model/bp.cpp \
		Data/Model/bss.cpp \
		Data/Model/cabinet.cpp \
		Data/Model/charger.cpp \
		Data/Model/localdatabase.cpp \
		Data/Model/swaprecord.cpp \
		Data/Model/user.cpp \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.cpp \
		Data/Reposistory/SwapRecordRepo/soundexecution.cpp \
		Data/Reposistory/SwapRecordRepo/swaprecordrepo.cpp \
		UI/bpview.cpp \
		UI/login.cpp \
		UI/mainwindow.cpp \
		UI/swapview.cpp \
		UI/userview.cpp \
		Util/cabcomhelper.cpp \
		bssmqttclient.cpp \
		cabinetcom.cpp \
		main.cpp \
		Data/Datasource/localsqlitedb.cpp \
		UI/continue.cpp qrc_sources.cpp \
		moc_localdatabase.cpp \
		moc_bsshttpmethod.cpp \
		moc_soundexecution.cpp \
		moc_swaprecordrepo.cpp \
		moc_bpview.cpp \
		moc_login.cpp \
		moc_mainwindow.cpp \
		moc_swapview.cpp \
		moc_userview.cpp \
		moc_cabcomhelper.cpp \
		moc_bssmqttclient.cpp \
		moc_cabinetcom.cpp \
		moc_continue.cpp
OBJECTS       = linkdirector.o \
		basemodel.o \
		bp.o \
		bss.o \
		cabinet.o \
		charger.o \
		localdatabase.o \
		swaprecord.o \
		user.o \
		bsshttpmethod.o \
		soundexecution.o \
		swaprecordrepo.o \
		bpview.o \
		login.o \
		mainwindow.o \
		swapview.o \
		userview.o \
		cabcomhelper.o \
		bssmqttclient.o \
		cabinetcom.o \
		main.o \
		localsqlitedb.o \
		continue.o \
		qrc_sources.o \
		moc_localdatabase.o \
		moc_bsshttpmethod.o \
		moc_soundexecution.o \
		moc_swaprecordrepo.o \
		moc_bpview.o \
		moc_login.o \
		moc_mainwindow.o \
		moc_swapview.o \
		moc_userview.o \
		moc_cabcomhelper.o \
		moc_bssmqttclient.o \
		moc_cabinetcom.o \
		moc_continue.o
DIST          = UI/img/Custom \
		Size \
		- \
		29.png \
		UI/img/Custom \
		Size \
		- \
		30.png \
		UI/img/Custom \
		Size \
		- \
		9.png \
		UI/img/Custom \
		Size \
		– \
		1.png \
		UI/img/Custom \
		Size \
		– \
		11.png \
		UI/img/Custom \
		Size \
		– \
		12.png \
		UI/img/Custom \
		Size \
		– \
		13.png \
		UI/img/Custom \
		Size \
		– \
		14.png \
		UI/img/Custom \
		Size \
		– \
		15.png \
		UI/img/Custom \
		Size \
		– \
		16.png \
		UI/img/Custom \
		Size \
		– \
		17.png \
		UI/img/Custom \
		Size \
		– \
		18.png \
		UI/img/Custom \
		Size \
		– \
		19.png \
		UI/img/Custom \
		Size \
		– \
		29.png \
		UI/img/Custom \
		Size \
		– \
		5.png \
		UI/img/Custom \
		Size \
		– \
		6.png \
		UI/img/Custom \
		Size \
		– \
		7.png \
		UI/img/Custom \
		Size \
		– \
		8.png \
		UI/img/Custom \
		Size \
		– \
		9.png \
		UI/img/battery \
		station3.158.png \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bss-hmi.pro Data/Datasource/linkdirector.h \
		Data/Datasource/soundsDatasource.h \
		Data/Model/basemodel.h \
		Data/Model/bp.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/charger.h \
		Data/Model/localdatabase.h \
		Data/Model/swaprecord.h \
		Data/Model/user.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Reposistory/SwapRecordRepo/swaprecordrepo.h \
		UI/bpview.h \
		UI/login.h \
		UI/mainwindow.h \
		UI/swapview.h \
		UI/userview.h \
		Util/cabcomhelper.h \
		bssmqttclient.h \
		cabinetcom.h \
		Data/Datasource/localsqlitedb.h \
		UI/continue.h Data/Datasource/linkdirector.cpp \
		Data/Model/basemodel.cpp \
		Data/Model/bp.cpp \
		Data/Model/bss.cpp \
		Data/Model/cabinet.cpp \
		Data/Model/charger.cpp \
		Data/Model/localdatabase.cpp \
		Data/Model/swaprecord.cpp \
		Data/Model/user.cpp \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.cpp \
		Data/Reposistory/SwapRecordRepo/soundexecution.cpp \
		Data/Reposistory/SwapRecordRepo/swaprecordrepo.cpp \
		UI/bpview.cpp \
		UI/login.cpp \
		UI/mainwindow.cpp \
		UI/swapview.cpp \
		UI/userview.cpp \
		Util/cabcomhelper.cpp \
		bssmqttclient.cpp \
		cabinetcom.cpp \
		main.cpp \
		Data/Datasource/localsqlitedb.cpp \
		UI/continue.cpp
QMAKE_TARGET  = bss-hmi
DESTDIR       = 
TARGET        = bss-hmi


first: all
####### Build rules

$(TARGET): ui_login.h ui_swapview.h ui_bpview.h ui_mainwindow.h ui_userview.h ui_continue.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bss-hmi.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bss-hmi.pro \
		sources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Mqtt.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile bss-hmi.pro -config release
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
bss-hmi.pro:
sources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Mqtt.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile bss-hmi.pro -config release

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents sources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Data/Datasource/linkdirector.h Data/Datasource/soundsDatasource.h Data/Model/basemodel.h Data/Model/bp.h Data/Model/bss.h Data/Model/cabinet.h Data/Model/charger.h Data/Model/localdatabase.h Data/Model/swaprecord.h Data/Model/user.h Data/Reposistory/SwapRecordRepo/bsshttpmethod.h Data/Reposistory/SwapRecordRepo/soundexecution.h Data/Reposistory/SwapRecordRepo/swaprecordrepo.h UI/bpview.h UI/login.h UI/mainwindow.h UI/swapview.h UI/userview.h Util/cabcomhelper.h bssmqttclient.h cabinetcom.h Data/Datasource/localsqlitedb.h UI/continue.h $(DISTDIR)/
	$(COPY_FILE) --parents Data/Datasource/linkdirector.cpp Data/Model/basemodel.cpp Data/Model/bp.cpp Data/Model/bss.cpp Data/Model/cabinet.cpp Data/Model/charger.cpp Data/Model/localdatabase.cpp Data/Model/swaprecord.cpp Data/Model/user.cpp Data/Reposistory/SwapRecordRepo/bsshttpmethod.cpp Data/Reposistory/SwapRecordRepo/soundexecution.cpp Data/Reposistory/SwapRecordRepo/swaprecordrepo.cpp UI/bpview.cpp UI/login.cpp UI/mainwindow.cpp UI/swapview.cpp UI/userview.cpp Util/cabcomhelper.cpp bssmqttclient.cpp cabinetcom.cpp main.cpp Data/Datasource/localsqlitedb.cpp UI/continue.cpp $(DISTDIR)/
	$(COPY_FILE) --parents UI/login.ui UI/swapview.ui UI/bpview.ui UI/mainwindow.ui UI/userview.ui UI/bpview.ui UI/continue.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_sources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_sources.cpp
qrc_sources.cpp: sources.qrc \
		/usr/lib/qt5/bin/rcc \
		UI/sound/voices/1.mp3 \
		UI/sound/voices/login-view.mp3 \
		UI/sound/voices/2.mp3 \
		UI/sound/voices/3.mp3 \
		UI/sound/voices/4.mp3 \
		UI/sound/voices/5.mp3 \
		UI/sound/voices/6.mp3 \
		UI/sound/voices/wrong-pass.mp3 \
		UI/sound/voices/bat-run-out.mp3 \
		UI/sound/voices/open-door.mp3 \
		UI/sound/voices/userview.mp3 \
		UI/sound/voices/bpview.mp3 \
		UI/sound/voices/continue.mp3 \
		UI/sound/voices/thank-for-sevice.mp3 \
		UI/sound/voices/checking-battery.mp3 \
		UI/sound/voices/close-door.mp3 \
		UI/sound/voices/suceess-swap-recervie-pin-number.mp3 \
		UI/sound/voices/put-pin-into-cab.mp3 \
		UI/sound/voices/bat-assign-timeout.mp3 \
		UI/images/userview.png \
		UI/images/login
	/usr/lib/qt5/bin/rcc -name sources sources.qrc -o qrc_sources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_localdatabase.cpp moc_bsshttpmethod.cpp moc_soundexecution.cpp moc_swaprecordrepo.cpp moc_bpview.cpp moc_login.cpp moc_mainwindow.cpp moc_swapview.cpp moc_userview.cpp moc_cabcomhelper.cpp moc_bssmqttclient.cpp moc_cabinetcom.cpp moc_continue.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_localdatabase.cpp moc_bsshttpmethod.cpp moc_soundexecution.cpp moc_swaprecordrepo.cpp moc_bpview.cpp moc_login.cpp moc_mainwindow.cpp moc_swapview.cpp moc_userview.cpp moc_cabcomhelper.cpp moc_bssmqttclient.cpp moc_cabinetcom.cpp moc_continue.cpp
moc_localdatabase.cpp: Data/Model/swaprecord.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/localdatabase.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Data/Model/localdatabase.h -o moc_localdatabase.cpp

moc_bsshttpmethod.cpp: Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/user.h \
		Data/Model/swaprecord.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Data/Reposistory/SwapRecordRepo/bsshttpmethod.h -o moc_bsshttpmethod.cpp

moc_soundexecution.cpp: Data/Datasource/soundsDatasource.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Data/Reposistory/SwapRecordRepo/soundexecution.h -o moc_soundexecution.cpp

moc_swaprecordrepo.cpp: Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		Data/Model/swaprecord.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/user.h \
		Data/Reposistory/SwapRecordRepo/swaprecordrepo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Data/Reposistory/SwapRecordRepo/swaprecordrepo.h -o moc_swaprecordrepo.cpp

moc_bpview.cpp: Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		UI/bpview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/bpview.h -o moc_bpview.cpp

moc_login.cpp: bssmqttclient.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/swaprecord.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		cabinetcom.h \
		Util/cabcomhelper.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		UI/login.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/login.h -o moc_login.cpp

moc_mainwindow.cpp: Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/mainwindow.h -o moc_mainwindow.cpp

moc_swapview.cpp: Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ViewModel/bpviewmodel.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/continue.h \
		UI/swapview.h \
		UI/swapview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/swapview.h -o moc_swapview.cpp

moc_userview.cpp: Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		Data/Model/user.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Data/Model/bp.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/userview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/userview.h -o moc_userview.cpp

moc_cabcomhelper.cpp: Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Util/cabcomhelper.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Util/cabcomhelper.h -o moc_cabcomhelper.cpp

moc_bssmqttclient.cpp: Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/swaprecord.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		bssmqttclient.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include bssmqttclient.h -o moc_bssmqttclient.cpp

moc_cabinetcom.cpp: Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		cabinetcom.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cabinetcom.h -o moc_cabinetcom.cpp

moc_continue.cpp: cabinetcom.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/swapview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ViewModel/bpviewmodel.h \
		UI/continue.h \
		UI/continue.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tuan/Desktop/bss-hmi/bss-hmi-qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtMqtt -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UI/continue.h -o moc_continue.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_login.h ui_swapview.h ui_bpview.h ui_mainwindow.h ui_userview.h ui_bpview.h ui_continue.h
compiler_uic_clean:
	-$(DEL_FILE) ui_login.h ui_swapview.h ui_bpview.h ui_mainwindow.h ui_userview.h ui_bpview.h ui_continue.h
ui_login.h: UI/login.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/login.ui -o ui_login.h

ui_swapview.h: UI/swapview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/swapview.ui -o ui_swapview.h

ui_bpview.h: UI/bpview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/bpview.ui -o ui_bpview.h

ui_mainwindow.h: UI/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/mainwindow.ui -o ui_mainwindow.h

ui_userview.h: UI/userview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/userview.ui -o ui_userview.h

ui_bpview.h: UI/bpview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/bpview.ui -o ui_bpview.h

ui_continue.h: UI/continue.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic UI/continue.ui -o ui_continue.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

linkdirector.o: Data/Datasource/linkdirector.cpp Data/Datasource/linkdirector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linkdirector.o Data/Datasource/linkdirector.cpp

basemodel.o: Data/Model/basemodel.cpp Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basemodel.o Data/Model/basemodel.cpp

bp.o: Data/Model/bp.cpp Data/Model/bp.h \
		Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bp.o Data/Model/bp.cpp

bss.o: Data/Model/bss.cpp Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bss.o Data/Model/bss.cpp

cabinet.o: Data/Model/cabinet.cpp Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cabinet.o Data/Model/cabinet.cpp

charger.o: Data/Model/charger.cpp Data/Model/charger.h \
		Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charger.o Data/Model/charger.cpp

localdatabase.o: Data/Model/localdatabase.cpp Data/Model/localdatabase.h \
		Data/Model/swaprecord.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localdatabase.o Data/Model/localdatabase.cpp

swaprecord.o: Data/Model/swaprecord.cpp Data/Model/swaprecord.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swaprecord.o Data/Model/swaprecord.cpp

user.o: Data/Model/user.cpp Data/Model/user.h \
		Data/Model/basemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o Data/Model/user.cpp

bsshttpmethod.o: Data/Reposistory/SwapRecordRepo/bsshttpmethod.cpp Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/user.h \
		Data/Model/swaprecord.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bsshttpmethod.o Data/Reposistory/SwapRecordRepo/bsshttpmethod.cpp

soundexecution.o: Data/Reposistory/SwapRecordRepo/soundexecution.cpp Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundexecution.o Data/Reposistory/SwapRecordRepo/soundexecution.cpp

swaprecordrepo.o: Data/Reposistory/SwapRecordRepo/swaprecordrepo.cpp Data/Reposistory/SwapRecordRepo/swaprecordrepo.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		Data/Model/swaprecord.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swaprecordrepo.o Data/Reposistory/SwapRecordRepo/swaprecordrepo.cpp

bpview.o: UI/bpview.cpp UI/bpview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/cabinet.h \
		ui_bpview.h \
		UI/swapview.h \
		ViewModel/bpviewmodel.h \
		cabinetcom.h \
		Data/Model/bss.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/continue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bpview.o UI/bpview.cpp

login.o: UI/login.cpp UI/login.h \
		bssmqttclient.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/swaprecord.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		cabinetcom.h \
		Util/cabcomhelper.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ui_login.h \
		UI/swapview.h \
		ViewModel/bpviewmodel.h \
		UI/continue.h \
		UI/userview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o UI/login.cpp

mainwindow.o: UI/mainwindow.cpp UI/mainwindow.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		ui_mainwindow.h \
		UI/swapview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ViewModel/bpviewmodel.h \
		UI/continue.h \
		UI/login.h \
		bssmqttclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o UI/mainwindow.cpp

swapview.o: UI/swapview.cpp UI/swapview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ViewModel/bpviewmodel.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/continue.h \
		ui_swapview.h \
		UI/bpview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swapview.o UI/swapview.cpp

userview.o: UI/userview.cpp UI/userview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		Data/Model/user.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Data/Model/bp.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		ui_userview.h \
		UI/swapview.h \
		ViewModel/bpviewmodel.h \
		UI/continue.h \
		UI/bpview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userview.o UI/userview.cpp

cabcomhelper.o: Util/cabcomhelper.cpp Util/cabcomhelper.h \
		Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cabcomhelper.o Util/cabcomhelper.cpp

bssmqttclient.o: bssmqttclient.cpp bssmqttclient.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/swaprecord.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bssmqttclient.o bssmqttclient.cpp

cabinetcom.o: cabinetcom.cpp cabinetcom.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cabinetcom.o cabinetcom.cpp

main.o: main.cpp UI/mainwindow.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		cabinetcom.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/bpview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		UI/login.h \
		bssmqttclient.h \
		Data/Reposistory/SwapRecordRepo/swaprecordrepo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

localsqlitedb.o: Data/Datasource/localsqlitedb.cpp Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localsqlitedb.o Data/Datasource/localsqlitedb.cpp

continue.o: UI/continue.cpp UI/continue.h \
		cabinetcom.h \
		Data/Model/bp.h \
		Data/Model/basemodel.h \
		Data/Model/bss.h \
		Data/Model/cabinet.h \
		Util/cabcomhelper.h \
		Data/Model/swaprecord.h \
		Data/Reposistory/SwapRecordRepo/bsshttpmethod.h \
		Data/Model/user.h \
		Data/Datasource/localsqlitedb.h \
		Data/Datasource/linkdirector.h \
		UI/swapview.h \
		Data/Reposistory/SwapRecordRepo/soundexecution.h \
		Data/Datasource/soundsDatasource.h \
		ViewModel/bpviewmodel.h \
		ui_continue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o continue.o UI/continue.cpp

qrc_sources.o: qrc_sources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_sources.o qrc_sources.cpp

moc_localdatabase.o: moc_localdatabase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localdatabase.o moc_localdatabase.cpp

moc_bsshttpmethod.o: moc_bsshttpmethod.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bsshttpmethod.o moc_bsshttpmethod.cpp

moc_soundexecution.o: moc_soundexecution.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundexecution.o moc_soundexecution.cpp

moc_swaprecordrepo.o: moc_swaprecordrepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_swaprecordrepo.o moc_swaprecordrepo.cpp

moc_bpview.o: moc_bpview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bpview.o moc_bpview.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_swapview.o: moc_swapview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_swapview.o moc_swapview.cpp

moc_userview.o: moc_userview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userview.o moc_userview.cpp

moc_cabcomhelper.o: moc_cabcomhelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cabcomhelper.o moc_cabcomhelper.cpp

moc_bssmqttclient.o: moc_bssmqttclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bssmqttclient.o moc_bssmqttclient.cpp

moc_cabinetcom.o: moc_cabinetcom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cabinetcom.o moc_cabinetcom.cpp

moc_continue.o: moc_continue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_continue.o moc_continue.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/bss-hmi/bin || mkdir -p $(INSTALL_ROOT)/opt/bss-hmi/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/bss-hmi/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/bss-hmi/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/bss-hmi/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/bss-hmi/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

